# Node.js with Angular
# Build a Node.js project that uses Angular.

trigger:
- develop
- staging
- main

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self
  persistCredentials: true

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js 20.x'

- script: |
    npm install -g @angular/cli@20.x
    npm install
  displayName: 'Install Dependencies'

# Build for Production (main branch)
- script: |
    ng build -c production
  displayName: 'Build Production'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')

# Build for Staging (staging branch)
- script: |
    ng build -c uat
  displayName: 'Build Staging'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/staging')

# Build for Development (develop branch or other)
- script: |
    ng build -c dev
  displayName: 'Build Development'
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables['Build.SourceBranch'], 'refs/heads/staging'))

# Publish the built 'dist' directory as the pipeline artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifact: drop'
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'drop'
    publishLocation: 'Container'
